services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: qrcodeservice
    ports:
      - 27017:27017
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-1}
    volumes:
      - "localstack-data:/data/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  mongodb-data:
  localstack-data:
